name: breff_editor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  file_picker: ^6.1.1
  provider: ^6.0.0
  file_selector: ^1.0.1
  get: '>=4.6.6' 
  # gets 5.0.0 RC
  google_fonts: '^6.1.0'
  desktop_window: '^0.4.0'
  flutter_rename_app_plus3: '1.2.3'
  tabbed_view: '1.17.0'
  multi_split_view: '2.4.0'
  flutter_animate: '4.4.0'
  toggle_switch: '2.1.0'
  flex_color_picker: '3.3.0'
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: false
  ios: false
  image_path: "TL.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

flutter_rename_app_plus3:
  application_name: "TL's Breff Editor"
  dart_package_name: breff_editor
  application_id: com.android.tl_breff_editor
  bundle_id: com.ios.tl_breff_editor
  android_package_name: com.breff_editor.app
  ios_bundle_name: TL's Breff Editor
