import 'package:flutter/material.dart';

class SubFileData extends ChangeNotifier {
  List<String> splitAtExcl(String str, int index) {
    return [str.substring(0, index), str.substring(index, str.length)];
  }

  String first(String str, int index) {
    return str.substring(0, index);
  }

  String chop(String str, int index) {
    return str.substring(index, str.length);
  }

  int offset;
  int lenDataBytes;
  String bytes;
  late String otherBytes;
  late String emBytes;
  // assuming emitter has size 0x14c
  late String emitterShape;
  late String emitterLife;
  late String particleLife;
  late String particleLifeRandom;
  late String inheritChildParticleTranslation;
  late String emitIntervalRand;
  late String emitRandom;
  late String emissionRate;
  late String emitStart;
  late String emitEnd;
  late String emitInterval;
  late String inheritParticleTranslation;
  late String inheritChildEmmitterTransformation;
  late String emitterDims;
  late String emitDiversion;
  late String randomVel;
  late String unknownFlags;
  late String emitFlags;
  late String randomMoment;
  late String powerRadiation;
  late String powerYAxisVal;
  late String powerRandom;
  late String powerNormal;
  late String diffEmitNormal;
  late String powerSpec;
  late String diffSpec;
  late String emAngle;
  late String scale;
  late String rot;
  late String transl;
  late String LODNearest;
  late String LODFurthest;
  late String LODMinEm;
  late String LODAlpha;
  late String randSeed;
  late String unknown0;
  late String drawFlagsBitfield;
  late String alphaComp0;
  late String alphaComp1;
  late String alphaCompOperation;
  late String numTEVStages;
  late String unknown1;
  late String indTEVEnabled;
  late String textureUsedTEV;
  late String TEVColInputSources;
  late String TEVOperations;
  late String alphaInputTEV;
  late String alphaTEVOperations;
  late String constColSelectors;
  late String constAlphaSelectors;
  late String blendModeType;
  late String blendSourceFactor;
  late String blendDestFactor;
  late String blendOperation;
  late String assignPartColTEVColRegisters;
  late String assignPartAlphTEVAlphRegisters;
  late String ZCompFunct;
  late String alphFlickType;
  late String alphFlickCycleLen;
  late String alphFlickMaxCycleRandDev;
  late String alphFlickAmpl;
  late String lightingMode;
  late String lightingType;
  late String lightingAmbCol;
  late String lightDiffCol;
  late String lightRadius;
  late String lightPos;
  late String indTexMat;
  late String indTexScale; //sbyte
  late String pivotX;
  late String pivotY;
  late String padding0;
  late String particleType;
  late String particleTypeOpt;
  late String movementType;
  late String rotAxis;
  late String gabiHelp0;
  late String gabiHelp1;
  late String gabiHelp2;
  late String padding1;
  late String zOffset;
  late String lenParticleDat;

  ////// PARTICLE
  late String partBytes;
  late String col1Primary;
  late String col1Secondary;
  late String col2Primary;
  late String col2Secondary;
  late String sizePart;
  late String scalePart;
  late String rotPart;
  late String texScale1;
  late String texScale2;
  late String texScale3;
  late String texRot;
  late String texTrans1;
  late String texTrans2;
  late String texTrans3;
  late String mTexture1;
  late String mTexture2;
  late String mTexture3;
  late String textureWrap;
  late String textureReverse;
  late String alphaCompRef0;
  late String alphaCompRef1;
  late String rotOffsetRand1;
  late String rotOffsetRand2;
  late String rotOffsetRand3;
  late String rotOffset;
  late String lenTexRef1;
  late String texRef1;
  late String lenTexRef2;
  late String texRef2;
  late String lenTexRef3;
  late String texRef3;
  ////// ANIMATION
  late String animationData;

  SubFileData(
      {required this.bytes, required this.offset, required this.lenDataBytes}) {
    String thisBytes = splitAtExcl(bytes, lenDataBytes)[0];
    otherBytes = splitAtExcl(thisBytes, lenDataBytes)[1];
    String emSize = thisBytes.substring(4, 8);
    int emSizeInt = int.parse(emSize, radix: 16);
    String emData =
        thisBytes.substring(8, emSizeInt); // the first header is already read
    String partAndAnimData = splitAtExcl(thisBytes, emSizeInt)[1];

    parseThis(emData, partAndAnimData);
  }

  String getStr() {
    StringBuffer out = StringBuffer();
    out.write("0000"); // pointer to effect name
    out.write(emBytes);
    out.write(unknownFlags);
    out.write(emitFlags);
    out.write(emitterShape);
    out.write(emitterLife);
    out.write(particleLife);
    out.write(particleLifeRandom);
    out.write(inheritChildParticleTranslation);
    out.write(emitIntervalRand);
    out.write(emitRandom);
    out.write(emissionRate);
    out.write(emitStart);
    out.write(emitEnd);
    out.write(emitInterval);
    out.write(inheritParticleTranslation);
    out.write(inheritChildEmmitterTransformation);
    out.write(emitterDims);
    out.write(emitDiversion);
    out.write(randomVel);
    out.write(randomMoment);
    out.write(randomMoment);
    out.write(powerRadiation);
    out.write(powerYAxisVal);
    out.write(powerRandom);
    out.write(powerNormal);
    out.write(diffEmitNormal);
    out.write(powerSpec);
    out.write(diffSpec);
    out.write(emAngle);
    out.write(scale);
    out.write(rot);
    out.write(transl);
    out.write(LODNearest);
    out.write(LODFurthest);
    out.write(LODMinEm);
    out.write(LODAlpha);
    out.write(randSeed);
    out.write(unknown0);
    out.write(drawFlagsBitfield);
    out.write(alphaComp0);
    out.write(alphaComp1);
    out.write(alphaCompOperation);
    out.write(numTEVStages);
    out.write(unknown1);
    out.write(indTEVEnabled);
    out.write(textureUsedTEV);
    out.write(TEVColInputSources);
    out.write(TEVOperations);
    out.write(alphaInputTEV);
    out.write(alphaTEVOperations);
    out.write(constColSelectors);
    out.write(constAlphaSelectors);
    out.write(blendModeType);
    out.write(blendSourceFactor);
    out.write(blendDestFactor);
    out.write(blendOperation);
    out.write(assignPartColTEVColRegisters);
    out.write(assignPartAlphTEVAlphRegisters);
    out.write(ZCompFunct);
    out.write(alphFlickType);
    out.write(alphFlickCycleLen);
    out.write(alphFlickMaxCycleRandDev);
    out.write(alphFlickAmpl);
    out.write(lightingMode);
    out.write(lightingType);
    out.write(lightingAmbCol);
    out.write(lightDiffCol);
    out.write(lightRadius);
    out.write(lightPos);
    out.write(indTexMat);
    out.write(pivotX);
    out.write(pivotY);
    out.write(padding0);
    out.write(particleType);
    out.write(particleTypeOpt);
    out.write(movementType);
    out.write(rotAxis);
    out.write(gabiHelp0);
    out.write(gabiHelp1);
    out.write(gabiHelp2);
    out.write(padding1);
    out.write(zOffset);
    out.write(lenParticleDat);
    out.write(partBytes);
    out.write(col1Primary);
    out.write(col1Secondary);
    out.write(col2Primary);
    out.write(col2Secondary);
    out.write(sizePart);
    out.write(scalePart);
    out.write(rotPart);
    out.write(texScale1);
    out.write(texScale2);
    out.write(texScale3);
    out.write(texRot);
    out.write(texTrans1);
    out.write(texTrans2);
    out.write(texTrans3);
    out.write(mTexture1);
    out.write(mTexture2);
    out.write(mTexture3);
    out.write(textureWrap);
    out.write(textureReverse);
    out.write(alphaCompRef0);
    out.write(alphaCompRef1);
    out.write(rotOffsetRand1);
    out.write(rotOffsetRand2);
    out.write(rotOffsetRand3);
    out.write(rotOffset);
    out.write(lenTexRef1);
    out.write(texRef1);
    out.write(lenTexRef2);
    out.write(texRef2);
    out.write(lenTexRef3);
    out.write(texRef3);
    out.write(animationData);
    return out.toString();
  }

  void parseThis(emData, partAndAnimData) {
    unknown0 = first(emData, 4);
    emData = chop(emData, 4);
    emitFlags = first(emData, 3);
    emitterShape = first(emData, 1);
    emitterLife = first(emData, 2);
    particleLife = first(emData, 2);
    particleLifeRandom = first(emData, 1);
    inheritChildParticleTranslation = first(emData, 1);
    emitIntervalRand = first(emData, 1);
    emitRandom = first(emData, 1);
    emissionRate = first(emData, 4);
    emitStart = first(emData, 2);
    emitEnd = first(emData, 2);
    emitInterval = first(emData, 2);
    inheritParticleTranslation = first(emData, 1);
    inheritChildEmmitterTransformation = first(emData, 1);
    emitterDims = first(emData, 18);
    emitDiversion = first(emData, 2);
    randomVel = first(emData, 1);
    randomMoment = first(emData, 1);
    randomMoment = first(emData, 4);
    powerRadiation = first(emData, 4);
    powerYAxisVal = first(emData, 4);
    powerRandom = first(emData, 4);
    powerNormal = first(emData, 4);
    diffEmitNormal = first(emData, 4);
    powerSpec = first(emData, 4);
    diffSpec = first(emData, 4);
    emAngle = first(emData, 4);
    scale = first(emData, 12);
    rot = first(emData, 12);
    transl = first(emData, 12);
    LODNearest = first(emData, 1);
    LODFurthest = first(emData, 1);
    LODMinEm = first(emData, 1);
    LODAlpha = first(emData, 1);
    randSeed = first(emData, 4);
    unknown0 = first(emData, 8);
    drawFlagsBitfield = first(emData, 2);
    alphaComp0 = first(emData, 1);
    alphaComp1 = first(emData, 1);
    alphaCompOperation = first(emData, 1);
    numTEVStages = first(emData, 1);
    unknown1 = first(emData, 1);
    indTEVEnabled = first(emData, 1);
    textureUsedTEV = first(emData, 4);
    TEVColInputSources = first(emData, 12);
    TEVOperations = first(emData, x);
    alphaInputTEV = first(emData, x);
    alphaTEVOperations = first(emData, x);
    constColSelectors = first(emData, x);
    constAlphaSelectors = first(emData, x);
    blendModeType = first(emData, x);
    blendSourceFactor = first(emData, x);
    blendDestFactor = first(emData, x);
    blendOperation = first(emData, x);
    assignPartColTEVColRegisters = first(emData, x);
    assignPartAlphTEVAlphRegisters = first(emData, x);
    ZCompFunct = first(emData, x);
    alphFlickType = first(emData, x);
    alphFlickCycleLen = first(emData, x);
    alphFlickMaxCycleRandDev = first(emData, x);
    alphFlickAmpl = first(emData, x);
    lightingMode = first(emData, x);
    lightingType = first(emData, x);
    lightingAmbCol = first(emData, x);
    lightDiffCol = first(emData, x);
    lightRadius = first(emData, x);
    lightPos = first(emData, x);
    indTexMat = first(emData, x);
    pivotX = first(emData, x);
    pivotY = first(emData, x);
    padding0 = first(emData, x);
    particleType = first(emData, x);
    particleTypeOpt = first(emData, x);
    movementType = first(emData, x);
    rotAxis = first(emData, x);
    gabiHelp0 = first(emData, x);
    gabiHelp1 = first(emData, x);
    gabiHelp2 = first(emData, x);
    padding1 = first(emData, x);
    zOffset = first(emData, x);
    lenParticleDat = first(emData, x);
    partBytes = first(emData, x);
    col1Primary = first(emData, x);
    col1Secondary = first(emData, x);
    col2Primary = first(emData, x);
    col2Secondary = first(emData, x);
    sizePart = first(emData, x);
    scalePart = first(emData, x);
    rotPart = first(emData, x);
    texScale1 = first(emData, x);
    texScale2 = first(emData, x);
    texScale3 = first(emData, x);
    texRot = first(emData, x);
    texTrans1 = first(emData, x);
    texTrans2 = first(emData, x);
    texTrans3 = first(emData, x);
    mTexture1 = first(emData, x);
    mTexture2 = first(emData, x);
    mTexture3 = first(emData, x);
    textureWrap = first(emData, x);
    textureReverse = first(emData, x);
    alphaCompRef0 = first(emData, x);
    alphaCompRef1 = first(emData, x);
    rotOffsetRand1 = first(emData, x);
    rotOffsetRand2 = first(emData, x);
    rotOffsetRand3 = first(emData, x);
    rotOffset = first(emData, x);
    lenTexRef1 = first(emData, x);
    texRef1 = first(emData, x);
    lenTexRef2 = first(emData, x);
    texRef2 = first(emData, x);
    lenTexRef3 = first(emData, x);
    texRef3 = first(emData, x);
    animationData = first(emData, x);
  }

  String getOtherBytes() {
    return otherBytes;
  }
}
